---
# docker-ce / tasks / main

- name: Run {{ ansible_distribution }}-specific tasks for installing docker-ce
  include_tasks: debian.yml
  when: >
    ansible_distribution == 'Debian'
      and
    (
      ansible_lsb.major_release | int == 8
      or
      ansible_lsb.major_release | int == 9
    )

- name: Install python docker tools
  pip:
    name: "{{ python_tools }}"

- name: Ensure docker service is enabled and running
  service:
    name: docker
    state: started
    enabled: yes
  register: result_docker_service_running

- name: Add specified users to group docker
  user:
    name: "{{ item }}"
    groups: docker
  with_items: "{{ docker_group_users }}"
  when: result_install_docker_packages is success

