---
# common / tasks / apt

- name: update apt cache and upgrade as needed
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    cache_valid_time: "{{ (max_apt_cache_age_hours * 60 * 60) | int | abs }}"

- name: install common packages
  ansible.builtin.apt:
    pkg: "{{ common_packages }}"
    state: present
  register: common_tasks_debian_packages_installed
