---
# common / tasks / main

- name: Ensure timezone set to {{ local_timezone }}
  timezone:
    name: "{{ local_timezone }}"

- name: Ensure locale {{ local_locale }} exists
  locale_gen:
    name: "{{ local_locale }}"
    state: present

- name: Ensure keyboard defaults file uses correct model
  replace:
    path: /etc/default/keyboard
    regexp: '^(XKBMODEL)="[^"]*"'
    replace: '\1="pc104"'
  notify: regenerate keyboard-configuration

- name: Ensure keyboard defaults file uses correct layout
  replace:
    path: /etc/default/keyboard
    regexp: '^(XKBLAYOUT)="[^"]*"'
    replace: '\1="us"'
  notify: regenerate keyboard-configuration

- name: Install helpful {{ ansible_distribution }} packages.
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
