---
# docker.io / tasks / main

- name: run debian-specific tasks for installing docker.io
  include_tasks: debian.yml
  when: >
    ansible_distribution == 'Debian'
    and
    ansible_lsb.major_release | int >= 9

- name: install python support modules for Docker
  ansible.builtin.pip:
    name: "{{ python_tools }}"
    executable: pip3

- name: ensure docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: "yes"
  register: result_docker_service_running

- name: add specified users to group docker
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
  with_items: "{{ docker_group_users }}"
  when: result_install_docker_packages is success
