---
- name: Install packages to support cross-platform building
  apt:
    pkg: "{{ crossbuilding_packages }}"

- name: Shallow git clone of raspberrypi support repos
  git:
    repo: "{{ git_repo_stub }}/{{ item }}.git"
    depth: 1
    version: "HEAD"
    dest: "~/build/{{ item }}"
  with_items: "{{ git_repos }}"
  become_user: vagrant
  become: yes
  ignore_errors: yes

- name: Create linux/.direnv.armhf
  copy:
    content: |
      export ARCH=arm
      export KBUILD_DEBARCH=armhf
      export CROSS_COMPILE=arm-linux-gnueabihf-
      #export ARM_TOOLS=/home/vagrant/build/tools
      #export CROSS_COMPILE=$ARM_TOOLS/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
      export J="$( echo $(nproc) '*' 1.5 / 1 | bc)"
      echo "You can edit the 'EXTAVERSION = ' line in Makefile to have additional useful information appended to product names."
    dest: /home/vagrant/build/linux/.envrc.armhf
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Create linux/.direnv.arm64
  copy:
    content: |
      export ARCH=arm64
      export CROSS_COMPILE=aarch64-linux-gnu-
      #export ARM_TOOLS=/home/vagrant/build/tools
      #export CROSS_COMPILE=$ARM_TOOLS/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
      export J="$( echo $(nproc) '*' 1.5 / 1 | bc)"
      echo "You can edit the 'EXTAVERSION = ' line in Makefile to have additional useful information appended to product names."
    dest: /home/vagrant/build/linux/.envrc.arm64
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Create symlink to .envrc for desired platform
  file:
    src: .envrc.{{ kernel_arch }}
    path: /home/vagrant/build/linux/.envrc
    owner: vagrant
    group: vagrant
    state: link
  register: envrc_symlink
