---
# pi-gen / tasks

- name: install debian pi-gen support packages
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: clone pi-gen Github repo
  git:
    repo: "{{ pi_gen_repo }}"
    version: "master"
    depth: 1
    dest: "~/build/pi-gen"
  become_user: vagrant
  become: yes
  register: result_repo
  ignore_errors: yes

- name: handle apt-cacher-ng archive if file exists
  include_tasks: apt-cacher-ng-archive.yml
  when: result_repo is success

- name: build and run pi-gen apt-cacher-ng Docker container
  docker_service:
    project_src: "/home/vagrant/build/pi-gen/"
  when: result_docker_service_running is success

- name: run prepare-pi-gen-for-stage2-luaml script
  shell: /vagrant/src/prepare-pi-gen-for-stage2-luaml.sh >/dev/null
  args:
    chdir: /home/vagrant/build/pi-gen/
    creates: stage2-luaml/prerun.sh
  become_user: vagrant
  become: yes
  register: stage2_luaml
  when: result_repo is success
