---
# docker / vars / main

support_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

repo_key:
  id: "8D81803C0EBFCD88"
  url: "https://download.docker.com/linux/debian/gpg"

repo_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' }}"

repo_url: "https://download.docker.com/linux/debian"

docker_version_stub:
  "{{ (docker_version == '') | ternary('', '=' ~ docker_version) }}"

docker_pkgname: "{{ docker_package_name ~ docker_version_stub }}"

python_tools:
  - docker
  - docker-compose
