---
# docker.io / vars / main

support_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - python3-docker

repo_key:
  id: "8D81803C0EBFCD88"
  url: "https://download.docker.com/linux/debian/gpg"

repo_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' }}"

repo_url: "https://download.docker.com/linux/debian"

docker_version_stub:
  "{{ (docker_version == '') | ternary('', '=' ~ docker_version) }}"

docker_pkgname: "{{ 'docker.io' ~ docker_version_stub }}"

python_tools:
  - docker-compose
