---
# pi-gen / vars

pi_gen_support_packages:
  - libarchive-tools
  - coreutils
  - curl
  - debootstrap
  - dosfstools
  - file
  - git
  - grep
  - libcap2-bin
  - parted
  - qemu-user-static
  - quilt
  - rsync
  - udev
  - xxd
  - xz-utils
  - zerofree
  - zip

pi_gen_repo: "https://github.com/RPi-distro/pi-gen.git"
