---
- hosts: all
  become: yes
  remote_user: vagrant
  become_method: sudo
  become_user: root

  vars:
    raspberrypi_linux_version: "rpi-4.14.y"

  roles:
    - common
    - docker-ce
    - pi-gen
    - vagrant-user-env
    - img-workspace
    - linux-kernel-crossbuild
