---
- hosts: all
  become: yes
  remote_user: vagrant
  become_method: sudo
  become_user: root

  vars:
    kernel_arch: "armhf"

  roles:
    - common
    - docker-ce
    - pi-gen
    - vagrant-user-env
    - img-workspace
    - linux-kernel-crossbuild
