---
- hosts: all
  become: "yes"
  remote_user: vagrant
  become_method: sudo
  become_user: root

  vars:
    kernel_arch: "armhf"
    #
    # docker_version can be used to specify a specific
    # version such as '18.06.0~ce~3-0~ubuntu', otherwise
    # leave as an empty string ("") to install the
    # latest.
    #
    # You can use the command apt-get madison docker.io
    # on a Debian-based system where the Docker apt
    # repos have already been configured to get the
    # correct version information string.
    #
    docker_version: ""
    docker_group_users:
      - vagrant
    pigen_commit: "2019-09-26-raspbian-buster"

  roles:
    - common
    - vagrant-user-env
    - docker
    # - pi-gen
    # - img-workspace
    # - linux-kernel-crossbuild
