---
# img-workspace/tasks/main.yml

- name: Create img-workspace build directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/build/img-workspace"
  become_user: vagrant
  become: yes

