---
# docker-ce / vars / main

support_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common

repo_key:
  id: "8D81803C0EBFCD88"
  url: "https://download.docker.com/linux/debian/gpg"

repo_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' }}"

repo_url: "https://download.docker.com/linux/debian"

docker_version_stub: "{{ '=' ~ docker_version if docker_version is not '' }}"

docker_pkgname: "{{ 'docker-ce' ~ docker_version_stub }}"

python_tools:
  - docker-compose

