---

- name: regenerate keyboard-configuration
  shell: "/usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
